# Generated by Django 5.2.7 on 2025-10-09 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='Prospect',
            new_name='prospect',
        ),
        migrations.RenameField(
            model_name='opportunity',
            old_name='cloture_data',
            new_name='cloture_date',
        ),
        migrations.AddField(
            model_name='opportunity',
            name='probability_purcent',
            field=models.CharField(default='', max_length=20),
        ),
    ]
