# Generated by Django 5.2.7 on 2025-10-15 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_prospect_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='status',
            field=models.CharField(choices=[('Prospect', 'Prospect'), ('Client', 'Active')], default='Prospect', max_length=50),
        ),
        migrations.AlterField(
            model_name='account',
            name='status',
            field=models.CharField(choices=[('Prospect', 'Prospect'), ('Active_Client', 'Active Client'), ('Archived', 'Archived')], default='Prospect', max_length=20),
        ),
    ]
