# Generated by Django 5.2.7 on 2025-10-16 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_rename_result_activity_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospect',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prospect', to='crm.account'),
        ),
    ]
