# Generated by Django 5.2.7 on 2025-10-15 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_prospect_status_alter_account_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Service',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='product_name',
            new_name='service_name',
        ),
    ]
