# Generated by Django 5.2.7 on 2025-10-15 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_rename_product_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipeline',
            name='display_order',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
