# Generated by Django 5.2.7 on 2025-10-15 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_alter_pipeline_display_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipeline',
            name='is_closed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
